---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: demo-redis-cluster
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  persistentSpec:
    enabled: true
    storageClassName: standard
    volumeSize: 30Gi
  redisEnterpriseImageSpec:
    imagePullPolicy: IfNotPresent
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: redis-enterprise-ui
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
