---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: demo-redis-cluster
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    requests:
      cpu: "2"
      memory: "8Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
  persistentSpec:
    enabled: true
    storageClassName: ocs-external-storagecluster-ceph-rbd
    volumeSize: 30Gi
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: redis-enterprise-ui
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
  to:
    kind: Service
    name: demo-redis-cluster-ui
  port:
    targetPort: 8443
  tls:
    termination: passthrough
