---
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: database
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
  redisEnterpriseCluster:
    name: demo-redis-cluster
  type: redis
  memorySize: 1GB
  replication: true
  persistence: aofEverySecond
  tlsMode: enabled
  evictionPolicy: noeviction
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: database
  namespace: redis-enterprise
  labels:
    app.kubernetes.io/managed-by: "argocd"
spec:
  to:
    kind: Service
    name: redis-12000
  port:
    targetPort: 12000
  tls:
    termination: passthrough
