apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../overlays/persistent

patches:
  - path: patch.yaml
    target:
      group: app.redislabs.com
      version: v1alpha1
      kind: RedisEnterpriseDatabase
      name: database
replacements:
  - source:
      group: app.redislabs.com
      version: v1alpha1
      kind: RedisEnterpriseDatabase
      fieldPath: metadata.name
    targets:
      - select:
          group: route.openshift.io
          version: v1
          kind: Route
          name: database
        fieldPaths:
          - metadata.name
          - spec.to.name
