apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: persistent-prod
  namespace: redis-prod
  labels:
    team: prod-team
    environment: prod
    database-type: persistent
spec:
  redisEnterpriseCluster:
    name: demo-redis-cluster
  # Persistent settings - important data with AOF persistence
  memorySize: 4GB
  type: redis
  evictionPolicy: noeviction
  persistence: aofEverySecond
  replication: true