apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: persistent-prod
  namespace: redis-prod
  labels:
    team: prod-team
    environment: prod
    database-type: persistent
spec:
  redisEnterpriseCluster:
    name: demo-redis-cluster