apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../bases/redis-database

patches:
  - path: persistent.yaml
    target:
      group: app.redislabs.com
      version: v1alpha1
      kind: RedisEnterpriseDatabase
      name: database
