apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: database
spec:
  type: redis
  memorySize: 2GB
  evictionPolicy: noeviction
  persistence: aofEverySecond
  replication: true
